version: '3.9'

services:
  socks5:
    build: ./socks5
    restart: unless-stopped
    # ports:
    #   - 3081:1010
  httpp:
    build: ./http
    restart: unless-stopped
  s: 
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./target:/ca
      - ./nginx.s.conf:/etc/nginx/nginx.conf
    ports:
      - 1992:1992
      - 2024:2024
    depends_on:
      - socks5
  c: 
    image: nginx:alpine 
    restart: unless-stopped
    volumes:
      - ./target:/ca 
      - ./nginx.c.conf:/etc/nginx/nginx.conf 
    ports:
      - 1992:1992   
      - 2024:2024
