version: '3'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=chenxuke
      - PGDATA=/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4:7.7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - db
  mqtt:
    image: emqx:5.0.26
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./emqx/data:/opt/emqx/data
      # - ./emqx/etc:/opt/emqx/etc 
      - ./emqx/log:/opt/emqx/log
  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data 
