version: '3'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=chenxuke
      - PGDATA=/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4:7.7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - v-pgadmin:/var/lib/pgadmin
    depends_on:
      - db
  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data 
  mqtt:
    image: emqx/nanomq:latest
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8083:8083
    # volumes:
    #   - ./nanomq/nanomq.conf:/etc/nanomqt.confabcd

volumes:
  v-pgadmin: {}
